### ISSUE TITLE
Divisional Standings

### ISSUE THREAD

**Issue by ClamsChowder** [zcs-cs/Baseball-Reporter#12]
These are the division standings before this game:
Team Name, Number of Wins, Number of Losses, PCT
            Hens, 4, 2, 67,
            Clippers, 3, 3, 50,
            Bats, 3, 4, 43,
            Indians, 3, 5, 37

I would like this data to be returned as a 2d array where Hens = 1, Clippers = 2, Bats = 3 and Indians = 4

**Comment by Hunter-Bobeck** [comment]
You will need to access these statistics on a **statistic per team** basis. I will give examples for just the Indians and the Bats as there are only ever two teams in a game..
_You will find that Team A is the label for the Indians, while Team B is the label for the Bats. As you can probably tell, the boolean parameter specifies the team, where true designates Team A and false designates Team B._

**Team Names:** (for instance, "Indianapolis Indians")
String teamAName = data.teamName(true);
String teamBName = data.teamName(false);

_Note that you may also wish to use more colloquial team demonyms (for instance, the "Indians"):_
**_Team Demonyms:**_
String teamADemonym = data.teamDemonym(true);
String teamBDemonym = data.teamDemonym(false);

**Team Wins:**
int teamAWins = data.teamStandingsWins(true);
int teamBWins = data.teamStandingsWins(false);

**Team Losses:**
int teamALosses = data.teamStandingsLosses(true);
int teamBLosses = data.teamStandingsLosses(false);

**Team 'PCT's:**
[Please clarify 'PCT'. Win percentage? Another percentage? I await your clarification in order to give examples of such a method.]

Thanks!

**Comment by seckart1** [comment]
Thanks for doing this, Hunter.

**Comment by ClamsChowder** [comment]
PCT is win percentage, so wins/(wins+losses). Thanks.

**Comment by ClamsChowder** [comment]
Also, the reason why I need all the team statistics in the division is to be able to see if the win or loss of a team would move them up or down in ranking. My job is to make a sentence with that information.

**Comment by Hunter-Bobeck** [comment]
Aye Scotty.

**Team 'PCT's:**
int teamAPCT = data.teamStandingsPCT(true);
int teamBPCT = data.teamStandingsPCT(false);

So what kind of other teams data do we need exactly? Are there two other teams we need to look at? I guess I would need to add those data fields as well, but I'm not sure exactly how yet...

**Comment by ClamsChowder** [comment]
I guess I really only need the PCTs for the other two teams (Hens and Clippers). That data is included in my first post.

**Comment by Hunter-Bobeck** [comment]
I see, didn't realize that was real data! That's ironic. Thanks.

**Comment by Hunter-Bobeck** [comment]
Here are the remaining method examples..

_I also need to supply you with the demonyms for the other teams:_
**_Other Team Demonyms:**_
String teamCDemonym = data.otherTeamDemonym(true);
String teamDDemonym = data.otherTeamDemonym(false);

**Other Team PCTs:**
int teamCPCT = data.otherTeamStandingsPCT(true);
int teamDPCT = data.otherTeamStandingsPCT(false);

**Comment by ClamsChowder** [comment]
The data that I need was not inserted into these methods. The methods given to me in this post include the wins, losses and PCTs currently, but I need the data for the teams before the game we went to. This data is included in my first post. Thanks.

**Comment by seckart1** [comment]
And also thank you Elliot and Claire Berman, Rob, and Wesenberg.
