### ISSUE TITLE
Big Innings Data

### ISSUE THREAD

**Issue by abbeyjulian** [zcs-cs/Baseball-Reporter#8]
We need 2 int arrays, one containing Team A's score each inning (not cumulative, preferably) and the other score per inning for Team B.

We also need access to home run data - player, what inning, and how many runs were scored off that ball. Specific data format is flexible depending how y'all have that data.

**Comment by Hunter-Bobeck** [comment]
Due to the structure, I won't be giving you the player for a run, but rather a count of runs for each player, and for each run which inning it was during and how many runs were scored off of the ball. You can determine from that which player goes with which run.
Hopefully there is actually data somewhere for us to use for how many runs were scored off of the ball, that seems very specific!

**Comment by Hunter-Bobeck** [comment]
I'm proceeding to change balls' runs into RBI (moved under hits instead of runs).
